name: NuGet Package
on:
  push:
    branches:
      - main # Default release branch
    paths:
      - 'src/**'   
      - '.github/workflows/**'   
jobs:
  deploy:
    runs-on: windows-latest
    permissions:
      packages: write
      contents: read
    env:
      SLN_FILE_NAME: FSMSharp.sln
      PROJ: FSMSharp  
      NUGET_AUTH_TOKEN: ${{secrets.NUGET_PAT}}
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1.8.1
        with:
          #dotnet-version: '3.1.x' # SDK Version to use.
          source-url: https://nuget.pkg.github.com/Digitalroot-Valheim/index.json
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup NuGet.exe
        uses: nuget/setup-nuget@v1
        with:
          nuget-version: latest
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2
      - name: Restore packages
        run: nuget restore ${{ github.workspace }}\src\${{ env.SLN_FILE_NAME }}
      - name: Build
        run: dotnet build ${{ github.workspace }}\src\${{ env.SLN_FILE_NAME }} -c Release --no-restore --nologo
      - name: Test
        run: dotnet test ${{ github.workspace }}\src\${{ env.SLN_FILE_NAME }} -c Release --no-build --nologo
      - name: Create the package
        run: dotnet pack src/${{ env.PROJ }}\${{ env.PROJ }}.csproj -c Release --no-restore --no-build --nologo
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}\src\FSMSharp\bin\Release
      - name: Publish package to Digitalroot-Valheim nuget repository
        run: dotnet nuget push "${{ github.workspace }}\src\${{ env.PROJ }}\bin\Release\${{ env.PROJ }}.*.nupkg" --skip-duplicate

